name: ASP.NET Core CI/CD

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x' # Укажите нужную версию .NET Core SDK

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy
      run: |
        # Остановите текущее запущенное приложение, если оно есть
        sudo systemctl stop TestApi || true

        # Скопируйте опубликованные файлы в нужную директорию
        sudo cp -r ./publish/* /var/www/myapp/

        # Запустите приложение
        sudo systemctl start TestApi
